### ISSUE TITLE
Find SQL Local Host Server

### ISSUE THREAD

**Issue by ballinin512** [CS3398-Kree/CS3398-Kree-F2019#42]

**Comment by Doss-alt** [comment]
Considering using my Raspberry Pi to manage the database using mySQL and wordpress.

https://projects.raspberrypi.org/en/projects/lamp-web-server-with-wordpress/7
https://pimylifeup.com/raspberry-pi-mysql/

**Comment by Doss-alt** [comment]
Will try Raspberry Pi later today. If it's not a workable solution, will utilize XAMPP or AMPPS somehow.
 https://ampps.com/downloads
https://www.apachefriends.org/index.html

**Comment by Doss-alt** [comment]
After some research, Raspberry Pi configuration will take a lot of time.
