### ISSUE TITLE
Work on learning basics of javascript and HTML framework Shelby

### ISSUE THREAD

**Issue by bkownacki1** [CS3398-Kree/CS3398-Kree-F2019#7]
Research and study Javascript and HTML:
https://www.w3schools.com/js/

Optionally look into Bootstrap HTML5:
https://www.w3schools.com/bootstrap/ this is for Bootstrap 3 but Bootstrap 4 is the latest so may be worth looking into
Learn enough to get comfortable making a basic webpage that utilizes node.js and HTML5.

**Comment by Doss-alt** [comment]
Completed 23 of 57 parts of the tutorial for JS. Setback due to lack of understanding of how HTML works. Spending time to research HTML so that JS understanding is fruitfull.

**Comment by Doss-alt** [comment]
I have no experience with HTML, JS, or nodeJS. This is taking me a long time to understand so I will be splitting the work into separate parts.

**Comment by Doss-alt** [comment]
Created extremely basic HTML page with simple JS implemented in it. No CSS added yet.

**Comment by Doss-alt** [comment]
Total time spent on getting basic understanding of HTML and JS > 6 hours.
